remote_theme: just-the-docs/just-the-docs
logo: "/images/sfulogo.png"
footer_content: "Copyright &copy; 2022 SFU"


just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    courseresources:
      permalink: "/_courseresources/"
      output: true

callouts:
  careful:
    title: Careful
    color: red

