remote_theme: just-the-docs/just-the-docs
logo: "/images/sfulogo.png"
footer_content: "Copyright &copy; 2022 SFU"



# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  courseresources:
    permalink: "/_courseresources/bruh.md/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    courseresources:
      # Give the collection a name
      name: Course Resources
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true




callouts:
  careful:
    title: Careful
    color: red

